[package]
name = "impl-display"
decription = "Implementation of trait 'Display'"
version = "0.1.0"
edition = "2021"
authors = ["DrakeN-inc <t.me/DrakeN_inc>"]
license = "MIT"
repository = "https://github.com/DrakeN-inc/rust-add-macro/tree/main/impl-display"

[lib]
proc_macro = true

[dependencies]
