[package]
name = "add_macro-impl_fromstr"
decription = "Implementation of trait 'FromStr'"
version = "0.1.0"
edition = "2021"
authors = ["DrakeN-inc <t.me/DrakeN-inc>"]
license = "MIT"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.36"
syn = "2.0.68"
