[package]
name = "add-macro-impl-display"
decription = "Implementation of trait 'Display'"
version = "0.1.0"
edition = "2021"
authors = ["DrakeN-inc <t.me/DrakeN-inc>"]
license = "MIT"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.68"
